### ISSUE TITLE
TypeError: Cannot read property 'optionalDependencies' of undefined

### ISSUE THREAD

**Issue by lookfirst** [dominictarr/npmd-resolve#16]
`npmd-resolve npmd`

/usr/local/lib/node_modules/npmd-resolve/resolve-tree.js:98
            opts.optional === false ? {} : opts.pkg.optionalDependencies
                                                   ^
TypeError: Cannot read property 'optionalDependencies' of undefined
    at /usr/local/lib/node_modules/npmd-resolve/resolve-tree.js:98:52
    at /usr/local/lib/node_modules/npmd-resolve/node_modules/pull-traverse/index.js:41:21
    at Array.<anonymous> (/usr/local/lib/node_modules/npmd-resolve/node_modules/pull-traverse/index.js:8:7)
    at Array.next (/usr/local/lib/node_modules/npmd-resolve/node_modules/pull-traverse/index.js:26:13)
    at next (/usr/local/lib/node_modules/npmd-resolve/node_modules/pull-cat/index.js:27:19)
    at /usr/local/lib/node_modules/npmd-resolve/node_modules/pull-cat/index.js:37:13
    at Array.<anonymous> (/usr/local/lib/node_modules/npmd-resolve/node_modules/pull-stream/sources.js:29:5)
    at next (/usr/local/lib/node_modules/npmd-resolve/node_modules/pull-cat/index.js:27:19)
    at /usr/local/lib/node_modules/npmd-resolve/node_modules/pull-cat/index.js:42:9
    at next (/usr/local/lib/node_modules/npmd-resolve/node_modules/pull-stream/sinks.js:7:7)

**Comment by dominictarr** [comment]
fixed in 7.8.1

**Comment by lookfirst** [comment]
thanks.
